esphome:
  name: oiltanksensor
  friendly_name: oiltanksensor
  

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "9tVvupIpMeTRTXD92cVJ4YkiLkYDlGUu2nCVqoEYAwQ="

ota:
  platform: esphome
  password: "15f2bfd2b242cb8bf6b52ac30625be09"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# Optional manual IP
  manual_ip:
    static_ip: 192.168.1.151
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "oiltanksensor Fallback Hotspot"
    password: "NfxTg3w5mfDp"

captive_portal:

# Enable Web server.
web_server:
  port: 80
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: oiltank_sensor ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: oiltank_sensor IP
    ssid:
      name: oiltank_sensor SSID
    bssid:
      name: oiltank_sensor BSSID

# Exposed switches.
# Switch to restart the sensor.   
switch:
  - platform: restart
    name: "oiltank_sensor Restart"

sensor:
  # Uptime sensor.
  - platform: uptime
    name: oiltank_sensor Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: oiltank_sensor WiFi Signal
    update_interval: 60s

# Wifi signal sensor.
  - platform: wifi_signal
    name: oiltank_sensor_wifi
    update_interval: 600s
    unit_of_measurement: '%'
    filters:
    - lambda: |-
       if (x <= -100) {
         return 0;
       } else {
         if (x >= -50) {
           return 100;
         } else {
           return 2 * (x + 100);
         }
       }

  - platform: ultrasonic
    accuracy_decimals: 2
    trigger_pin:
      number: GPIO17
      inverted: true
    echo_pin:
      number: GPIO18
    timeout: 5.98m  
    pulse_time: 20us
    name: "Oil Tank Sensor"
    id: oil_tank_sensor
    update_interval: 10min
    unit_of_measurement: "m"    
    filters:
     - filter_out: nan
    on_value:
       then:
         - sensor.template.publish:
             id: oiltank_liters              
             state: !lambda 'const int volume =1000;const float distfull=0.2; const float distempty=1.2; const float m=(volume/(distfull-distempty)); const float b=volume-m*distfull; return m*x+b ;'
         - sensor.template.publish:
             id: oiltank_percent
             state: !lambda 'const int volume =1000; return id(oiltank_liters).state/volume *100;' 
 

    # Templates for calculated liter & percent
  - platform: template
    name: oiltank liters
    id: oiltank_liters
    icon: 'mdi:water'
    unit_of_measurement: 'l'
    accuracy_decimals: 0

  - platform: template
    name: oiltank percent
    id: oiltank_percent
    icon: 'mdi:water-percent'
    unit_of_measurement: '%'

  

